apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiapi
  labels:
    app: apiapi
spec:
  template:
    metadata:
      labels:
        app: apiapi
    spec:
      volumes:
      - name: transfer-config
        configMap:
          name: transfer-config
      containers:
      - image: gcr.io/apisquare-222314/apiapi-staging:latest
        name: apiapi
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        volumeMounts:
        - name: transfer-config
          mountPath: /creds/transfer-config.json
          subPath: transfer-config.json
        env:
        - name: APPLICATION_ENV
          value: staging
        - name: NODE_ENV
          value: staging
        - name: PORT
          value: "80"
        - name: NODE_PATH
          value: "."
        - name: DATABASE_NAME
          value: transfer
        - name: DATABASE_HOST
          value: "35.197.242.114"
        - name: DATABASE_USER
          value: "msqapi1"
        - name: DATABASE_PASS
          value: "m.ysql*api1"
        - name: DATABASE_POOL_MIN
          value: "1"
        - name: DATABASE_POOL_MAX
          value: "4"
        - name: DATABASE_PORT
          value: "3306"
        - name: COOKIE_DURATION
          value: "2592000000"
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_USER
          value: rabbitmq
        - name: RABBITMQ_PASS
          value: rabbitmq