module.exports = {
    ADMINISTRATOR: 'administrator',
    PERMANENT: 'permanent',
    TOKEN_ERROR: "TokenExpiredError",
    USER_TOKEN_EXPIRY: "user_token_expiry",
    NEW_TASK_CREATED: "New Task was created",
    TASK_DETAILS_UPDATED: "Task details was updated",
    REQUEST_ACCESS_MAPPER: "request_access_mapper",
    TASK_DELETED: "Task was deleted",
    DEFAULT: "default",
    RESET_TOKEN_EXPIRY: "reset_token_expiry",
    TASK_TYPE_REASON: "task_type_reason",
    INITIATE: "initiate",
    COMPLETE: "complete",
};